### ISSUE TITLE
[Feature] Lite install without docker/db

### ISSUE THREAD

**Issue by vdeleeuw** [BioCla/Discord-MusicBot#14]
Hello 👋

## Is your feature request related to a problem? Please describe.
I have just installed this version from v5. It runs pretty well for me right now.
I launched the bot without docker/database and it was pretty sketchy, i will call this kind of installation as a "lite version" 

here are the "problems" i had to deal with :

1. No information in the readme file (at project root) to setup a lite bot for poor hardware (like raspberry pi for me)
2. Editing the file config.js is prone to syntax error 

## Describe the ideal solution

1. To me, lite version should be the default one as i think this is more a start&go kind of bot and should be more documented in the root readme.md
2. One or two file .env / .env.lite in root folder with key=value would be much more convenient to edit and an example file would be appreciated

## Describe alternatives you've considered

Maybe a sh script to help setup with inputs for a lite deploy ?
In fact we dont need a lot to run, like bot name + token + client id&secret + lavalink address
It could help a lot of users who have trouble to launch the bot

**Comment by BioCla** [comment]
Great Suggestion!
I'll look into making the process easier to make the bot executable from any hardware.
As I evaluate the best way to implement the Lite version I'll keep track of the missing documentation and gradually expand on the existing one.

I'll keep this issue open for more suggestions (and later convert to discussion if needed) until I find a proper way to implement this and actually integrate it into the project.

**Comment by BioCla** [comment]
This has been implemented to work with the backend only right now!
Look forward to seeing the same procedure implemented for the frontend as well in future updates.

The current modus to start the bot without the docker configuration is fairly similar to that of the original v5 [Explained here](https://github.com/BioCla/Discord-MusicBot/blob/feature/DJSv14/djs-bot/README.md)
But, given that v5.1 uses docker a new command has been made to support non-docker configurations as well:
`make up no-docker`
