### ISSUE TITLE
Playing a  song while another is playing does not add it to the Queue

### ISSUE THREAD

**Issue by Slacker101** [BioCla/Discord-MusicBot#2]
Playing a  song while another is playing does not add it to the Queue. The bot still ends after finishing.

Additionally, the message for auto queue implies that it's enabled or disabled but either way it seems to be always disabled.

**Comment by BioCla** [comment]
> Playing a song while another is playing does not add it to the Queue. The bot still ends after finishing.
Thanks, this went under the radar 
> Additionally, the message for auto queue implies that it's enabled or disabled but either way it seems to be always disabled.
I had already marked to fix this as I had noticed it as well. It is more of an issue with the engine than the bot itself. Switching to the Erela engine should work for now

**Comment by BioCla** [comment]
This has actually revealed another bug:
Playing a song while another is playing can disconnect the bot and end the queue at once while using Cosmicord's engine

**Comment by BioCla** [comment]
> Playing a song while another is playing does not add it to the Queue. The bot still ends after finishing.
> 
> Additionally, the message for auto queue implies that it's enabled or disabled but either way it seems to be always disabled.

Both these issues can be fixed by switching to Erela's engine. In the meanwhile I've set the default one to Erela and I'll keep working towards making Cosmicord more compatible with the bot.
I'll close the issue while keeping in mind that Cosmicord needs to be fixed, thanks for the report :)
